// Socket.IO event name constants for EmployeeOS real-time features.

const SOCKET_EVENTS = {
  LEAVE_REQUEST_CREATED: 'leave:request-created',
  LEAVE_REQUEST_APPROVED: 'leave:request-approved',
  LEAVE_REQUEST_REJECTED: 'leave:request-rejected',
  LEAVE_REQUEST_CANCELLED: 'leave:request-cancelled',
  LEAVE_BALANCE_UPDATED: 'leave:balance-updated',
  NOTIFICATION_NEW: 'notification:new',
  NOTIFICATION_READ: 'notification:read',
  ATTENDANCE_UPDATED: 'attendance:updated',
  DASHBOARD_LEAVE_UPDATED: 'dashboard:leave-updated',
  CONNECTED: 'connected',
  UNAUTHORIZED: 'unauthorized',
  ERROR: 'error',
  PROJECT_CREATED: 'project:created',
  PROJECT_UPDATED: 'project:updated',
  PROJECT_DELETED: 'project:deleted',
  PROJECT_MEMBER_ADDED: 'project:member-added',
  PROJECT_MEMBER_REMOVED: 'project:member-removed',
  TASK_CREATED: 'task:created',
  TASK_UPDATED: 'task:updated',
  TASK_ASSIGNED: 'task:assigned',
  TASK_UNASSIGNED: 'task:unassigned',
  TASK_STATUS_CHANGED: 'task:status-changed',
  TASK_PRIORITY_CHANGED: 'task:priority-changed',
  TASK_DELETED: 'task:deleted',
  TASK_COMMENT_ADDED: 'task:comment-added',
  TASK_COMMENT_UPDATED: 'task:comment-updated',
  TASK_COMMENT_DELETED: 'task:comment-deleted',
  TASK_ACTIVITY_CREATED: 'task:activity-created',
  PERFORMANCE_CYCLE_CREATED: 'performance:cycle-created',
  PERFORMANCE_CYCLE_UPDATED: 'performance:cycle-updated',
  GOAL_CREATED: 'goal:created',
  GOAL_UPDATED: 'goal:updated',
  GOAL_PROGRESS_UPDATED: 'goal:progress-updated',
  GOAL_COMPLETED: 'goal:completed',
  GOAL_AT_RISK: 'goal:at-risk',
  KPI_CREATED: 'kpi:created',
  KPI_UPDATED: 'kpi:updated',
  KPI_VALUE_UPDATED: 'kpi:value-updated',
  REVIEW_STARTED: 'review:started',
  REVIEW_ASSIGNED: 'review:assigned',
  REVIEW_SUBMITTED: 'review:submitted',
  REVIEW_COMPLETED: 'review:completed',
  REVIEW_REOPENED: 'review:reopened',
  FEEDBACK_CREATED: 'feedback:created',
  FEEDBACK_SUBMITTED: 'feedback:submitted',
  FEEDBACK_REQUESTED: 'feedback:requested',
  PERFORMANCE_SCORE_UPDATED: 'performance:score-updated',
};

module.exports = SOCKET_EVENTS;
